import { landingImages } from "../assets/landing/images";
import type { MemberRecord } from "./memberFormUtils";

const L = landingImages.leaders;
const T = landingImages.testimonials;

export const MEMBERS_SEED: MemberRecord[] = [
  {
    id: 1,
    nom: "Kabongo Mwamba",
    prenom: "Jean-Pierre",
    email: "jp.kabongo@email.com",
    telephone: "+243 81 234 5678",
    dateNaissance: "1992-03-15",
    departement: "Administration",
    categorie: "Homme",
    responsabilite: "Responsable centre",
    dateDebutPratique: "2015-04-01",
    abonnementVaguePaix: true,
    sokahan: true,
    quartier: "Gombe",
    chapitre: "Chapitre 1 – Kinshasa",
    district: "District Nord",
    groupe: "Groupe A",
    statut: "Actif",
    adhesion: "2026-03-15",
    abonnement: true,
    photo: L.centre,
    totalDons: 120000,
  },
  {
    id: 2,
    nom: "Mbeki Nkosi",
    prenom: "Amara",
    email: "amara.mbeki@email.com",
    telephone: "+242 06 789 0123",
    dateNaissance: "1997-07-22",
    departement: "Culture",
    categorie: "Femme",
    responsabilite: "Responsable chapitre",
    dateDebutPratique: "2018-08-10",
    abonnementVaguePaix: true,
    sokahan: true,
    quartier: "Poto-Poto",
    chapitre: "Chapitre 2 – Brazzaville",
    district: "District Sud",
    groupe: "Groupe B",
    statut: "Actif",
    adhesion: "2026-07-22",
    abonnement: true,
    photo: L.femme,
    totalDons: 85000,
  },
  {
    id: 3,
    nom: "Fontaine",
    prenom: "Cécile",
    email: "c.fontaine@email.fr",
    telephone: "+33 6 12 34 56 78",
    dateNaissance: "2001-01-10",
    departement: "Jeunesse",
    categorie: "Jeune fille",
    responsabilite: "Membre simple",
    dateDebutPratique: "2021-02-01",
    abonnementVaguePaix: false,
    sokahan: false,
    quartier: "Belleville",
    chapitre: "Chapitre 3 – Paris",
    district: "District Ouest",
    groupe: "Groupe C",
    statut: "Actif",
    adhesion: "2025-01-10",
    abonnement: false,
    photo: L.jeuneFille,
    totalDons: 45000,
  },
  {
    id: 4,
    nom: "Konaté",
    prenom: "Ibrahim",
    email: "i.konate@email.ci",
    telephone: "+225 07 456 7890",
    dateNaissance: "2004-11-03",
    departement: "Avenir",
    categorie: "Avenir",
    responsabilite: "Membre simple",
    dateDebutPratique: "2023-01-15",
    abonnementVaguePaix: false,
    sokahan: false,
    quartier: "Plateau",
    chapitre: "Chapitre 4 – Abidjan",
    district: "District Est",
    groupe: "Groupe D",
    statut: "En attente",
    adhesion: "2026-08-01",
    abonnement: false,
    photo: L.jeuneHomme,
    totalDons: 10000,
  },
  {
    id: 5,
    nom: "Tshisekedi Wa",
    prenom: "Marie-Claire",
    email: "mc.tshisekedi@email.com",
    telephone: "+243 99 876 5432",
    dateNaissance: "1990-06-28",
    departement: "Éducation",
    categorie: "Femme",
    responsabilite: "Responsable district",
    dateDebutPratique: "2012-09-01",
    abonnementVaguePaix: true,
    sokahan: true,
    quartier: "Kalamu",
    chapitre: "Chapitre 1 – Kinshasa",
    district: "District Nord",
    groupe: "Groupe A",
    statut: "Actif",
    adhesion: "2025-06-28",
    abonnement: true,
    photo: T.woman,
    totalDons: 200000,
  },
  {
    id: 6,
    nom: "Diallo",
    prenom: "Ousmane",
    email: "o.diallo@email.ci",
    telephone: "+225 05 111 2233",
    dateNaissance: "1988-02-14",
    departement: "Santé",
    categorie: "Homme",
    responsabilite: "Responsable groupe",
    dateDebutPratique: "2010-03-01",
    abonnementVaguePaix: false,
    sokahan: false,
    quartier: "Yopougon",
    chapitre: "Chapitre 4 – Abidjan",
    district: "District Nord",
    groupe: "Groupe B",
    statut: "Suspendu",
    adhesion: "2026-02-14",
    abonnement: false,
    photo: L.homme,
    totalDons: 0,
  },
  {
    id: 7,
    nom: "Ngandu",
    prenom: "Patrick",
    email: "p.ngandu@email.com",
    telephone: "+243 82 333 4444",
    dateNaissance: "1995-09-05",
    departement: "Logistique",
    categorie: "Homme",
    responsabilite: "Responsable groupe",
    dateDebutPratique: "2017-10-01",
    abonnementVaguePaix: true,
    sokahan: true,
    quartier: "Lingwala",
    chapitre: "Chapitre 1 – Kinshasa",
    district: "District Sud",
    groupe: "Groupe C",
    statut: "Actif",
    adhesion: "2026-08-03",
    abonnement: true,
    photo: L.chapitre1,
    totalDons: 75000,
  },
  {
    id: 8,
    nom: "Lemaire",
    prenom: "Sophie",
    email: "s.lemaire@email.fr",
    telephone: "+33 7 88 99 00 11",
    dateNaissance: "1994-04-19",
    departement: "Communication",
    categorie: "Femme",
    responsabilite: "Responsable chapitre",
    dateDebutPratique: "2016-05-01",
    abonnementVaguePaix: true,
    sokahan: true,
    quartier: "Montreuil",
    chapitre: "Chapitre 3 – Paris",
    district: "District Ouest",
    groupe: "Groupe D",
    statut: "Actif",
    adhesion: "2026-04-19",
    abonnement: true,
    photo: L.chapitre3,
    totalDons: 95000,
  },
  {
    id: 9,
    nom: "Bakary",
    prenom: "Moussa",
    email: "m.bakary@email.cg",
    telephone: "+242 05 678 9012",
    dateNaissance: "1998-12-01",
    departement: "Avenir",
    categorie: "Jeune homme",
    responsabilite: "Membre simple",
    dateDebutPratique: "2022-01-01",
    abonnementVaguePaix: false,
    sokahan: false,
    quartier: "Moungali",
    chapitre: "Chapitre 2 – Brazzaville",
    district: "District Est",
    groupe: "Groupe A",
    statut: "Actif",
    adhesion: "2025-12-01",
    abonnement: false,
    photo: L.chapitre2,
    totalDons: 110000,
  },
  {
    id: 10,
    nom: "Deschamps",
    prenom: "Laurent",
    email: "l.deschamps@email.fr",
    telephone: "+33 6 55 44 33 22",
    dateNaissance: "2002-01-15",
    departement: "Jeunesse",
    categorie: "Jeune homme",
    responsabilite: "Membre simple",
    dateDebutPratique: "2024-02-01",
    abonnementVaguePaix: false,
    sokahan: false,
    quartier: "Nanterre",
    chapitre: "Chapitre 3 – Paris",
    district: "District Nord",
    groupe: "Groupe B",
    statut: "En attente",
    adhesion: "2026-07-15",
    abonnement: false,
    photo: L.jeunesse,
    totalDons: 5000,
  },
];

export function memberFullName(member: Pick<MemberRecord, "prenom" | "nom">) {
  return `${member.prenom} ${member.nom}`;
}

export function findMemberPhotoByName(fullName: string, members: MemberRecord[] = MEMBERS_SEED) {
  const match = members.find((member) => memberFullName(member) === fullName);
  return match?.photo || "";
}
